import numpy as np

from algorithms.hill_climbing import (generate_initial_solution,generate_successors,random_restart_hill_climbing)


def test_generate_initial_solution(): #Check that we generate a solution with the correct number of hospitals
    solution = generate_initial_solution(100)
    assert len(solution) == 100


def test_solution_is_binary(): #Check that our solution contains only 0s and 1s
    solution = generate_initial_solution(100)
    assert np.all((solution == 0) | (solution == 1))

 
#def test_generate_successors(): #Check that we generate add/remove and swap successors
    #solution = np.array([1,0,1,0])
    #successors = generate_successors(solution)
   # assert len(successors) == 8
def test_generate_successors():
    solution = np.array([1, 0, 1, 0])

    successors = generate_successors(solution)

    assert len(successors) >= len(solution)

def test_successors_change_valid_bits(): #Check that each successor is generated by either one flip or one swap
    solution = np.array([1, 0, 1, 0])
    successors = generate_successors(solution)
    for successor in successors:
        diff = np.sum(solution != successor)
        assert diff == 1 or diff == 2


def test_hill_climbing_runs():  # Check that algorithm runs without errors
    population_points = np.random.uniform(0, 100, size=(20, 2))
    weights = np.random.randint( 1, 11, size=20)
    candidate_hospitals = np.random.uniform(0, 100, size=(20, 2))
    solution, cost = random_restart_hill_climbing(population_points,weights,candidate_hospitals,lambd=10,restart_times=2)
    assert solution is not None
    assert cost >= 0